### PR TITLE
Login Validation Fix ACC-398

### LINKED ISSUE #18: Log Into Site Causes Critical Error
When logging into the site, the login fails and a critical site error is caused. 

To reproduce:
1. Install acc_user_importer plugin.
2. Manually create a user and assign them a non-admin role. 
3. Try log in with this user. 
4. The log in is unsuccessful and the critical error message is displayed. 

If you disable the acc_user_importer plugin, the user is able to log in successfully. 

It looks like the method `acc_validate_user_login` is generating an error when a non-admin tries to log in and does not have an active membership. I suspect that this could be related to the fact that the fields `membership_status` and `expiry` may not exist for the users? 

The desired behaviour is that an unsuccessful error message for a non-admin user should be displayed instead of a critical error being raised.

### PR DESCRIPTION
**Pull request by tjg37**
Addresses Issues:
1.  https://github.com/acc-wp/acc_user_importer/issues/18. 
2. [ACC-398](https://alpineclubofcanada.atlassian.net/browse/ACC-398)

The fix required three steps: 
1. Update `acc_validate_user_login` to accept both a user or an error. This fixed the critical error that I was experiencing due to the hook being called twice. 
3. Add the `acc_um_custom_authenticate_error_codes` hook to register the custom `membership_validation_error` errors with UM. This ensured that the errors are displayed correctly. 
4. Updated version number accordingly. 

Example of the desired output below:
Screen Shot 2024-09-10 at 1 54 18 PM

### CODE REVIEW

File: admin/acc-user-manager.php [hunk 1]
```diff
@@ -2,6 +2,13 @@
 
 add_filter( 'wp_authenticate_user', 'acc_validate_user_login' );
 
+add_filter( 'um_custom_authenticate_error_codes', 'acc_um_custom_authenticate_error_codes' );
+
+function acc_um_custom_authenticate_error_codes( $third_party_codes ) {
+      $third_party_codes[] = "membership_validation_error";
+ return $third_party_codes;
```
Comment (francoisbessette) [inline admin/acc-user-manager.php]: Line 9 seems indented differently than line 8.

Comment (tjg37) [reply admin/acc-user-manager.php]: Fixed. 

It would be a good idea to also add a linter to the repo to automatically manage the indentations and styling.

Comment (francoisbessette) [reply admin/acc-user-manager.php]: Oh, it is possible to automate the formatting?  Sure.

**Comment by tjg37** [comment]
Hi Francois,

I added a PR<https://github.com/acc-wp/acc_user_importer/pull/20> that adds a commit hook to assist with the formatting.
[https://opengraph.githubassets.com/9c2413c30c0511bb59bb7a3680da9cc979e7ece35d2e07a9f5b6db117e7bcf76/acc-wp/acc_user_importer/pull/20]<https://github.com/acc-wp/acc_user_importer/pull/20>
Adding Prettier Commit Hook by tjg37 · Pull Request #20 · acc-wp/acc_user_importer<https://github.com/acc-wp/acc_user_importer/pull/20>
Adding Prettier Commit Hook to ensure code formatting is correct. When making a commit, Prettier will run on all changed files and will proceed to clean up the formatting if needed. Work Done: Ins...
github.com

________________________________
